// <auto-generated />
namespace BudgetTracker.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class added_products_categories : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(added_products_categories));
        
        string IMigrationMetadata.Id
        {
            get { return "201610271349215_added_products_categories"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
