//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BudgetTracker.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Transaction
    {
        public int ID { get; set; }
        public double Amount { get; set; }
        public Nullable<int> Product_ID { get; set; }
        public Nullable<int> Currency_ID { get; set; }
        public Nullable<int> User_ID { get; set; }
        public Nullable<System.DateTime> TransactionDate { get; set; }
    
        public virtual Currency Currency { get; set; }
        public virtual Product Product { get; set; }
        public virtual UserInfo UserInfo { get; set; }
    }
}
